# Generated by Django 6.0.3 on 2026-04-05 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('codigo_estudiante', models.CharField(max_length=30, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=20)),
                ('grado', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=10)),
                ('anio', models.PositiveIntegerField()),
                ('sede', models.CharField(max_length=100)),
                ('school_level', models.CharField(max_length=30)),
                ('nombre_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_padre', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_madre', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Confirmado', 'Confirmado'), ('Pendiente', 'Pendiente'), ('Retirado', 'Retirado'), ('Inactivo', 'Inactivo')], default='Confirmado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'db_table': 'students',
                'ordering': ['grado', 'grupo', 'apellidos', 'nombres'],
            },
        ),
    ]
