# Generated by Django 6.0.3 on 2026-04-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
