# Generated by Django 6.0.3 on 2026-04-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='foto_pos_x',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='student',
            name='foto_pos_y',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
