# Generated by Django 6.0.3 on 2026-04-08 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_foto_pos_x_student_foto_pos_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('nivel_desarrollo', models.PositiveSmallIntegerField(choices=[(1, 'Inicial'), (2, 'Básico'), (3, 'Intermedio'), (4, 'Alto'), (5, 'Sobresaliente')], default=3)),
                ('visible_dashboard', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='students.student')),
            ],
            options={
                'verbose_name': 'talento',
                'verbose_name_plural': 'talentos',
                'db_table': 'talents',
                'ordering': ['-nivel_desarrollo', 'titulo'],
            },
        ),
    ]
