# Generated by Django 6.0.3 on 2026-04-14 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'arquetipo',
                'verbose_name_plural': 'arquetipos',
                'db_table': 'archetypes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='strength',
            options={'ordering': ['-nivel_desarrollo', 'titulo'], 'verbose_name': 'habilidad socioemocional', 'verbose_name_plural': 'habilidades socioemocionales'},
        ),
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['-nivel_desarrollo', 'titulo'], 'verbose_name': 'habilidad técnica', 'verbose_name_plural': 'habilidades técnicas'},
        ),
        migrations.AddField(
            model_name='student',
            name='arquetipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.archetype'),
        ),
        migrations.CreateModel(
            name='SocioEmotionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('idg_dimension', models.CharField(blank=True, max_length=80, null=True)),
                ('nivel_desarrollo', models.PositiveSmallIntegerField(choices=[(1, 'Inicial'), (2, 'Básico'), (3, 'Intermedio'), (4, 'Alto'), (5, 'Sobresaliente')], default=3)),
                ('mentor_nivel', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Inicial'), (2, 'Básico'), (3, 'Intermedio'), (4, 'Alto'), (5, 'Sobresaliente')], null=True)),
                ('visible_dashboard', models.BooleanField(default=True)),
                ('comentario_estudiante', models.TextField(blank=True, null=True)),
                ('comentario_mentor', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquetipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio_emotional_skills', to='students.archetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socio_emotional_skills', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_socio_emotional_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'habilidad socioemocional nueva',
                'verbose_name_plural': 'habilidades socioemocionales nuevas',
                'db_table': 'socio_emotional_skills',
                'ordering': ['-nivel_desarrollo', 'titulo'],
                'unique_together': {('student', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('school_year', models.PositiveIntegerField(default=2026)),
                ('nivel_desarrollo', models.PositiveSmallIntegerField(choices=[(1, 'Inicial'), (2, 'Básico'), (3, 'Intermedio'), (4, 'Alto'), (5, 'Sobresaliente')], default=1)),
                ('progreso_porcentaje', models.PositiveSmallIntegerField(default=0)),
                ('visible_dashboard', models.BooleanField(default=True)),
                ('ruta_aprendizaje', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquetipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_skills', to='students.archetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='students.student')),
            ],
            options={
                'verbose_name': 'habilidad técnica nueva',
                'verbose_name_plural': 'habilidades técnicas nuevas',
                'db_table': 'technical_skills',
                'ordering': ['-nivel_desarrollo', 'titulo'],
                'unique_together': {('student', 'titulo', 'school_year')},
            },
        ),
    ]
